version: '3'

services:
  mongo:
    image: mongo
    container_name: my-mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "D:/Estudos/Java/Spring_Boot_Microservices_Projetct_Example/Docker/Volumes/MongoDB:/data/db"
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    container_name: my-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - mongo-compose-network

networks: 
  mongo-compose-network:
    driver: bridge